### ISSUE TITLE
Reactions not appearing on Disqus plugin

### ISSUE THREAD

**Issue by svijaykoushik** [svijaykoushik/blog#22]
Reactions even though enabled on Disqus dashboard, it's not appearing on the page's comment section.

**Comment by ishank-juneja** [comment]
Did this get resolved?

**Comment by ishank-juneja** [comment]
Never mind figured it out, it applies to new posts only and not retrospectively.

**Comment by svijaykoushik** [comment]
> Never mind figured it out, it applies to new posts only and not retrospectively.

@ishank-juneja Thanks you for figuring out. And I'm sorry for not replying to you in time
